# Generated by Django 4.2.2 on 2023-06-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_priority_alter_issue_status'),
        ('issues', '0003_auto_20230611_0938'),
    ]

    operations = [
    ]
